dist: trusty
sudo: required
language: php
php:
- 7.1
before_script:
- composer self-update
- composer install
addons:
  sonarcloud:
    organization: didatus-github
    token:
      secure: 2315e1bdbdbc0639637f117f66444ddd361efda8
jdk:
- oraclejdk8
script:
- composer test
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
